language: go

services:
  - docker

before_install:
- docker build --no-cache -t carmaldocker/estello .
- docker-compose up -d

script:
  - curl 127.0.0.1:8080
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker images
  - docker push carmaldocker/estello
