dist: xenial
jobs:
  include:
    - stage: build docker image
      script:
      - echo "C@rm@l123" | docker login -u "carmaldocker" --password-stdin
      - docker build -t carmaldocker/estello .
      - docker images
      - docker push carmaldocker/estello
