language: go

services:
- docker

env:
 global:
    - SERVER_IP_ADDRESS=207.246.89.240
    - DOCKER_IMAGE=carmaldocker/etsello
before_install:
# setup the key for deployment
- openssl aes-256-cbc -K $encrypted_a67e4c47b36a_key -iv $encrypted_a67e4c47b36a_iv
  -in deploy_key.enc -out ./deploy_key -d
- eval "$(ssh-agent -s)"
- chmod 600 ./deploy_key
- echo -e "Host $SERVER_IP_ADDRESS\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- ssh-add ./deploy_key
#test ssh connection
- ssh -i ./deploy_key root@207.246.89.240 pwd
# docker build steps
- docker build --no-cache -t carmaldocker/etsello .
- docker-compose up -d
- docker ps

script:
- curl 127.0.0.1:80
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker images
- docker push carmaldocker/etsello

after_success:
- scp -i ./deploy_key docker-compose.yaml etsello-deploy.sh root@207.246.89.240:/root/itsy-deploy-scripts
- ssh -i ./deploy_key root@207.246.89.240 chmod +x /root/itsy-deploy-scripts/etsello-deploy.sh
- ssh -i ./deploy_key root@207.246.89.240 /root/itsy-deploy-scripts/etsello-deploy.sh $DOCKER_IMAGE
